version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  php-pdlc:
      build:
          context: ./docker
          dockerfile: php.Dockerfile
      container_name: pdlc-php
      depends_on:
          - database-sql
      volumes:
          - './:/var/www/html:cached'

  nginx-pdlc:
      image: 'nginx:1.23.3'
      container_name: pdlc-nginx
      ports:
          - '81:80'
          # - '443:443'
      links:
          - 'php-pdlc'
      volumes:
          - './:/var/www/html:cached'
          - './config/nginx:/etc/nginx/conf.d:cached'

  database-sql:
      image: 'mariadb:10.7.8'
      container_name: pdlc-database-sql
      restart: 'on-failure'
      ports:
          - "3307:3306"
      environment:
          MYSQL_DATABASE: app
          MYSQL_ROOT_PASSWORD: root

networks: 
  default:
    name: pdlc
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
