name: Deploy
 
on:
  push:
    branches: [master]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
 
    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.APP_HOST }}
        USERNAME: ${{ secrets.APP_SECRET }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "web/les-pros-de-la-com.jamdev.tech/public_html"
 
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.APP_HOST }}
        USERNAME: ${{ secrets.APP_USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: ls
