# write a coutinuous delivery code that trigger when a push is made to the master branch
# and deploy the code to the server
# name: Deploy to server

# on:
#   push:
#     branches:
#       - master

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Deploy to server
#         uses: appleboy/scp-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           key: ${{ secrets.KEY }}
#           port: ${{ secrets.PORT }}
#           source: "./"
#           target: "/var/www/html"

# Path: .github\workflows\deploy.yaml



