name: CD
on:
  push:
    branches: [master]

jobs:
  deploy:
    run-on: ubuntu-lastest

    env:
      SSHPASS: ${{ secret.APP_PASS }}

    step:
      - uses: actions/checkout@v2

      - name: APT UPDATE and INSTALL SSHPASS
        run:
          sudo apt update && sudo apt install sshpass
      
      - name: test pwd
        sshpass -e ssh -o stricthostkeychecking=no ${{ secret.APP_USER }}@${{ secret.APP_PASS }}
        "cd web/les-pros-de-la-com.jamdev.tech/public_html/ &&
        git pull &&
        composer install &&
        php bin/console d:m:m -n"